### ISSUE TITLE
updateSlider is not defined

### ISSUE THREAD

**Issue by julianbolts** [michael-jerred/angular-ui-nouislider#3]
I got some errors when [running your directive within a custom directive](http://plnkr.co/edit/yG140JyI9tZsFdfskXl2?p=preview), due to updateSlider (line 94) not being defined. Please see my [pull request](https://github.com/michael-jerred/angular-ui-nouislider/pull/2).

Thanks

**Comment by michael-jerred** [comment]
Thanks! It's merged in now
